version: '2.4'

services:
  node-red:
    # image: sillium/docker-node-red-qnap:latest
    image: nodered/node-red:latest
    container_name: node-red
    hostname: docker-node-red
    ports:
      - 1880:1880/tcp
    volumes:
      - ./node-red-data/:/data/:rw
    # user: "999"
    restart: unless-stopped
    networks:
      qnet-static:
        ipv4_address: 192.168.65.3

networks:
  qnet-static:
    external: true
    name: qnet-static-ip-network
